title: Felo's Blog.
email: yangfeilong_2009@126.com
description: 立志，勤学，改过，责善
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  yangfeiffei

# Build settings
markdown: kramdown
theme: minima
highlight: true
permalink: pretty
#paginate: 3

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

timezone: Asia/Shang_Hai
links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "GitHub"
    url: http://github.com/yangfeiffei
